create database rapidoyet;
use rapidoyet;

SELECT COUNT(*) AS Total_Rows
FROM rapido;



-- 1.How many rides were completed successfully?
-- 2.What is the average ride duration in minutes? 
-- 3.Find the average ride distance for each vehicle type?
-- 4.Get the total number of canceled rides by customers?
-- 5.Which vehicle type receives better customer ratings?
-- 6.Top 5 customers who booked the highest number of rides?
-- 7.Which payment method is used?
-- 8.How much revenue was generated by Bike and Auto rides?( Revenue by vehicle type)
-- 9. Average ride time by vehicle type?
-- 10.Most common reason for incomplete rides?



-- 1.How many rides were completed successfully?
Create View Completed_Booking AS
SELECT * FROM rapido
WHERE Booking_Status='Completed';


# 1.How many rides were completed successfully?
select * from Completed_Booking;



-- 2.What is the average ride duration in minutes?
Create View Average_Ride_Duration AS
SELECT AVG(`Ride_Time(min)`) AS Average_Ride_Duration
FROM rapido;


# 2.What is the average ride duration in minutes?
select * from Average_Ride_Duration;


-- 3.Find the average ride distance for each vehicle type?
Create View Average_Ride_Distance_for_each_Vehicle_Type AS
SELECT Vehicle_Type,
       AVG(`Ride_Distance(km)`) AS Average_Ride_Distance
FROM rapido
GROUP BY Vehicle_Type;


# 3.Find the average ride distance for each vehicle type?
select * from Average_Ride_Distance_for_each_Vehicle_Type;


-- 4.Get the total number of canceled rides by customers?
CREATE VIEW Total_Canceled_Rides_By_Customer AS
SELECT COUNT(*) AS Total_Canceled_Rides_By_Customer
FROM rapido
WHERE Canceled_Rides_by_Customer = 1;


# 4.Get the total number of canceled rides by customers?
SELECT * FROM Total_Canceled_Rides_By_Customer;


-- 5.Which vehicle type receives better customer ratings?
CREATE VIEW Vehicle_Type_Customer_Rating AS
SELECT Vehicle_Type,
       ROUND(AVG(Customer_Rating), 2) AS Average_Customer_Rating
FROM rapido
GROUP BY Vehicle_Type
ORDER BY Average_Customer_Rating DESC;


# 5.Which vehicle type receives better customer ratings?
SELECT * FROM Vehicle_Type_Customer_Rating;


-- 6.Top 5 customers who booked the highest number of rides?
CREATE VIEW Top_5_Customers_who_Booked_Highest_Number_of_Rides AS
SELECT Customer_ID,
       COUNT(Booking_ID) AS Total_Rides
FROM rapido
GROUP BY Customer_ID
ORDER BY Total_Rides DESC
LIMIT 5;


# 6.Top 5 customers who booked the highest number of rides?
SELECT * FROM Top_5_Customers_who_Booked_Highest_Number_of_Rides;


-- 7.Which payment method is used?
CREATE VIEW Payment_Method_Used AS
SELECT Payment_Method,
       COUNT(*) AS Total_Transactions
FROM rapido
GROUP BY Payment_Method
ORDER BY Total_Transactions DESC
LIMIT 5;



# 7.Which payment method is used?
SELECT * FROM Payment_Method_Used;



-- 8.How much revenue was generated by Bike and Auto rides?( Revenue by vehicle type)
CREATE VIEW revenue_was_generated_by_Bike_and_Auto_rides AS
SELECT Vehicle_Type,
SUM(Booking_Value) AS Total_Revenue
FROM rapido
GROUP BY Vehicle_Type
ORDER BY Total_Revenue DESC;


# 8.How much revenue was generated by Bike and Auto rides?( Revenue by vehicle type)
SELECT * FROM revenue_was_generated_by_Bike_and_Auto_rides;


-- 9. Average ride time by vehicle type?
CREATE VIEW Average_ride_time_by_vehicle_time AS
SELECT Vehicle_Type,
AVG(`Ride_Time(min)`) AS Average_Ride_Time
FROM rapido
GROUP BY Vehicle_Type;


# 9. Average ride time by vehicle type?
SELECT * FROM Average_ride_time_by_vehicle_time;


-- 10.Most common reason for incomplete rides
Create View Common_Reasons_for_Incomplete_rides AS
SELECT Incomplete_Rides_Reason,
       COUNT(*) AS Total_Incomplete_Rides
FROM rapido
WHERE Incomplete_Rides = 1
GROUP BY Incomplete_Rides_Reason
ORDER BY Total_Incomplete_Rides DESC;


# 10.Most common reasons for incomplete rides
 select * from Common_Reasons_for_Incomplete_rides;



